server:
  port: 8094
spring:
  application:
    name: file
  cloud:
    nacos:
      server-addr: 127.0.0.1:8093
  datasource:
    username: root
    password: liuhao12345
    url: jdbc:mysql://localhost:3306/file?userSSL=false
    driver-class-name: com.mysql.jdbc.Driver