server:
  port: 8094
  jetty:
    max-http-form-post-size: 102400
spring:
  application:
    name: file
  cloud:
    nacos:
      server-addr: 127.0.0.1:8093
  datasource:
    username: root
    password: liuhao12345
    url: jdbc:mysql://localhost:3306/file?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
#      单个文件最大
      max-file-size: 100MB
#      多个文件最大
      max-request-size: 200MB
mybatis:
  mapper-locations: com/bycyjs/file/mapper/FileMapper.xml
