server:
  port: 8080
spring:
  application:
    name: service

  cloud:
    nacos:
      server-addr: 127.0.0.1:8093
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
