server:
  port: 8092
spring:
  application:
    name: user-nacos
  cloud:
    nacos:
      server-addr: localhost:8093
#      discovery:
#        username: nacos
#        password: nacos
#        namespace: pev