server:
  port: 8090
  jetty:
    max-http-form-post-size: 102400
spring:
  application:
    name: login
  cloud:
    nacos:
      server-addr: 127.0.0.1:8093
  datasource:
    username: root
    password: liuhao12345
    url: jdbc:mysql://localhost:3306/login?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.139.com
    # 发送者邮箱
    username: bycyjs@139.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: 61da71e67e2c14e5a700
    # 端口号465或者25
    port: 465
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          ssl:
            # 这里设为true时 端口号设为 465 设为false时 端口号设为25
            enable: true
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: password
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 500
          min-idle: 0
      lettuce:
        shutdown-timeout: 0







